/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicJoinRouteImport } from './routes/api/public/join'
import { Route as ApiPublicDiscordRegisterRouteImport } from './routes/api/public/discord-register'
import { Route as ApiPublicDiscordRouteImport } from './routes/api/public/discord'
import { Route as ApiPublicDataRouteImport } from './routes/api/public/data'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJoinRoute = ApiPublicJoinRouteImport.update({
  id: '/api/public/join',
  path: '/api/public/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordRegisterRoute =
  ApiPublicDiscordRegisterRouteImport.update({
    id: '/api/public/discord-register',
    path: '/api/public/discord-register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordRoute = ApiPublicDiscordRouteImport.update({
  id: '/api/public/discord',
  path: '/api/public/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDataRoute = ApiPublicDataRouteImport.update({
  id: '/api/public/data',
  path: '/api/public/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/data': typeof ApiPublicDataRoute
  '/api/public/discord': typeof ApiPublicDiscordRoute
  '/api/public/discord-register': typeof ApiPublicDiscordRegisterRoute
  '/api/public/join': typeof ApiPublicJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/data': typeof ApiPublicDataRoute
  '/api/public/discord': typeof ApiPublicDiscordRoute
  '/api/public/discord-register': typeof ApiPublicDiscordRegisterRoute
  '/api/public/join': typeof ApiPublicJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/data': typeof ApiPublicDataRoute
  '/api/public/discord': typeof ApiPublicDiscordRoute
  '/api/public/discord-register': typeof ApiPublicDiscordRegisterRoute
  '/api/public/join': typeof ApiPublicJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/data'
    | '/api/public/discord'
    | '/api/public/discord-register'
    | '/api/public/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/data'
    | '/api/public/discord'
    | '/api/public/discord-register'
    | '/api/public/join'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/data'
    | '/api/public/discord'
    | '/api/public/discord-register'
    | '/api/public/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicDataRoute: typeof ApiPublicDataRoute
  ApiPublicDiscordRoute: typeof ApiPublicDiscordRoute
  ApiPublicDiscordRegisterRoute: typeof ApiPublicDiscordRegisterRoute
  ApiPublicJoinRoute: typeof ApiPublicJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/join': {
      id: '/api/public/join'
      path: '/api/public/join'
      fullPath: '/api/public/join'
      preLoaderRoute: typeof ApiPublicJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-register': {
      id: '/api/public/discord-register'
      path: '/api/public/discord-register'
      fullPath: '/api/public/discord-register'
      preLoaderRoute: typeof ApiPublicDiscordRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord': {
      id: '/api/public/discord'
      path: '/api/public/discord'
      fullPath: '/api/public/discord'
      preLoaderRoute: typeof ApiPublicDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/data': {
      id: '/api/public/data'
      path: '/api/public/data'
      fullPath: '/api/public/data'
      preLoaderRoute: typeof ApiPublicDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicDataRoute: ApiPublicDataRoute,
  ApiPublicDiscordRoute: ApiPublicDiscordRoute,
  ApiPublicDiscordRegisterRoute: ApiPublicDiscordRegisterRoute,
  ApiPublicJoinRoute: ApiPublicJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
